### ISSUE TITLE
Update SwiftMailer v6 reference

### ISSUE THREAD

**Issue by Simounet** [FriendsOfPHP/security-advisories#321]
Hi there,
It seems like https://github.com/Roave/SecurityAdvisories/ is using information from this repo to check security issues. I can't install SwiftMailer v6.1.3 because there is only references to v4 and v5 here.
Can you help me out to fix this? I tried to make a PR on https://github.com/Roave/SecurityAdvisories/pull/50#pullrequestreview-158154475 but it seems not to be the right place. Should I do a PR with the v6 version but I don't have any security link about it?
Have a nice day.

**Comment by Ocramius** [comment]
Hmm, you may have misunderstood what that repository is for: those versions are blocked from being installed.

**Comment by xabbuh** [comment]
I guess you are rather trying to install Swiftmailer 6 with a PHP version that is not supported.

**Comment by fabpot** [comment]
Closing as this is not related to this repo. @xabbuh has probably guessed the issue.

**Comment by stof** [comment]
Well, what forbids installing swiftmailer 6 is `mailjet/mailjet-swiftmailer` which requires switftmailer `~5.4`, and you already have swiftmailer 6.1.3 in your project, while the partial update is not allowed to update it.

Use `composer require ... --update-with-dependencies` to allow composer to change the version of dependencies of the new package instead of forcing to keep the version you already use.
