### ISSUE TITLE
Wordpress advisories

### ISSUE THREAD

**Issue by MacGyer** [FriendsOfPHP/security-advisories#383]
Hey guys,

any chance to supply Wordpress security advisories?

Or is there no way, as the official WP repo (https://api.github.com/repos/wordpress/wordpress) does not provide composer support and one has to rely on unofficial sources like https://github.com/roots/wordpress or https://github.com/johnpbloch/wordpress?

Thanks for any thoughts on this.

Cheers

**Comment by fabpot** [comment]
This repository is open for all contributions. But if nobody submit vulns for Wordpress, we won't have them. Some projects try to automate the submissions, which is also an option. Anyway, closing for now as there is "core team" doing the work here.

**Comment by stof** [comment]
As there is no official wordpress composer pacjage, advisories would have to be published for each of the unofficial sources. As these seem to be normal composer package, there should be no issue submitting them here.

For wordpress plugins, it depends how they are managed through composer. The main blockage to including advisories here (besides the fact that someone needs to do the work, and the wordpress core team will probably not as they don't support composer officially) would be if `package name + version` would not uniquely identify a release due to weird things being done (this is why we reverted the inclusion of drupal-contrib advisories, because they reuse the same name+version for their 7.x and 8x plugins while they are different code).
